# Generated by Django 3.1.2 on 2021-09-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210909_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
